name: Deploy to Screeps

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy to Screeps
        uses: screeps/screeps-github@v1.1.0
        with:
          token: ${{ secrets.SCREEPS_TOKEN }}
          branch: main
